### ISSUE TITLE
State of package development

### ISSUE THREAD

**Issue by denrou** [senx/warp10-r#3]
First of all, thank you very much for the package.

I was wondering if this package was still under development or if you plan to release other versions in the near future. I work a lot with Warp10 database and needed better management for R users.
Therefore, [I forked the project](https://github.com/centreon/warp10-r) and made lot of changes on it. If you are still working on this package, would you like to share some of the thinking you plan on doing? I don't want to make a PR now since changes are profound, but I'd love to collaborate.

You can read the README of the fork for a better understanding of what I'm trying to achieve and I'd be happy to talk about some work we can do together to make R package more userfriendly.

**Comment by randomboolean** [comment]
Thanks for your interest in the package.
The feature of this package is to provide a simple way to  remotely execute warpscripts from R and retrieve the result in a convenient format, and for now we have no plan to develop it further.
However we'd love to hear about what could be done to improve it. Can you please send me an email at jean-charles.vialatte@senx.io so that we can schedule a call ?
